### ISSUE TITLE
Machine translation interactions are interfaced with GUI in the chat widget

### ISSUE THREAD

**Issue by kerlikur** [buerokratt/Machine-Translation-to-Buerokratt#15]
AS AN End User
I WANT TO see and use machine translation interactions and visual components in the chat widget
SO THAT I can see and use machine translation opportunities

### Acceptance Criteria:
- [ ] Display notifications related to machine translation. #6 
- [ ] The descriptive texts of the buttons and input field in the chat widget are in the selected/ identified language. #20 
- [ ] The details view is translated into the identified language. #3 
- [ ] Distinguishing machine translation in conversation. #10 
- [ ] Asking for feedback in the chat window is user-friendly and in a identified language. #13 
- [ ] The greeting message must be in the correct language. #29

**Comment by turnerrainer** [comment]
@kerlikur these ACs are covered in other issues.

**Comment by kerlikur** [comment]
@turnerrainer 
I grouped these issues so that it would be better to refer to the back-office and the chat widget separately in UI/UX solutions.
