### ISSUE TITLE
The machine translations answer must be seen

### ISSUE THREAD

**Issue by kerlikur** [buerokratt/Machine-Translation-to-Buerokratt#17]
AS A CSA
I WANT TO see the machine translation of the answer I write
SO THAT I can see how machine translated answer looks like

### Acceptance Criteria:
- [ ] The CSA is able to see the original message and the machine translated message
- [ ] Functionality to hide or show machine translation. #11 
- [ ] CSA's input is sent to machine translation after the CSA is done typing and presses button "Translate".
- [ ] CSA can modify the translation after translation #19 .
- [ ] Response is sent after confirmation #18  .

**Comment by turnerrainer** [comment]
@kerlikur is there an AC for when should this functionality be applied? After every typing / new word/sentence / some time (in seconds), pressing enter, etc?

**Comment by kerlikur** [comment]
@turnerrainer 
The machine translated text must be displayed for the CSA to see its content. At the moment, translation does not have to be active while writing, it may also be that the text is written and then the button is pressed to translate the text. In the future, translation should be more automatic.
