### ISSUE TITLE
Machine translation interactions are interfaced with GUI in the back office

### ISSUE THREAD

**Issue by kerlikur** [buerokratt/Machine-Translation-to-Buerokratt#27]
AS A CSA
I WANT TO see and use machine translation interactions and visual components in the back office
SO THAT I can see and use machine translation opportunities

### Acceptance Criteria:
- [ ] Each machine translation language separately has an option to turn language machine translation on and off in the back office administration module. #9
- [ ] The CSA must have the option to see answer machine translation. #17 
- [ ] In the back office the original and the translated conversation are distinguishable in the chat module. #21 
- [ ] The CSA can hide and show original messages in the back office under active conversation and chat history. #11 
- [ ] There is a language info/ field under the chat info in the back office. #8 
- [ ] CSA should have the opportunity to discard or modify the machine translation response. #19 
- [ ] CSA can validate the machine translation before sending response to the End User. #18 
- [ ] The End User last machine translated message must be visible under unanswered conversations. #30 
- [ ] The End User's communication language must be displayed in the unanswered chats column. #31 
- [ ] In the history tab, it must be possible to sort and filter conversations that have used machine translation. #32 
- [ ] In the history view has an option to download machine translated messages and modified machine translation. #33

**Comment by turnerrainer** [comment]
@kerlikur these ACs are covered in other issues.

**Comment by kerlikur** [comment]
@turnerrainer 
I grouped these issues so that it would be better to refer to the back-office and the chat widget separately in UI/UX solutions.
